before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: ZYfjIt2YgerYwsilGQ+UMixvPVA0Cw4yixXt9OVU6krNVJYBRW7yB5dfzIjcLwyr1nmHmF6BkuMYfyrvMuSlj5z72FzzVsFJhCqiFNG0Oimj1zPXkOXc3GSJGYXB/lpDAmlMnuzbjxSFipunMN7vFWznnqt96/nOsuuyNMmWleGSU7Wl4IpIKhZRd/qel+2A1Qaw0XQdssPu9fwc/GWV2M8BDbuG6Koaa9fCq+F4lhVp7n6eZzra468yu7ebaMlkS+4ZjFLSag2J5NeQx5GWBEY95vgsf6jXwvPu6h/bNLD064OD3UEjIt8KQJeXYvB2Wm0xoXzGeXdDhcp1zuvNLvACcrp4r4HIb9Syu3a3+iouwjyGrTLNDwnIANQNpX/AZPRQ609Xx5g5rLEJrdfuLMDqwWp5V9eXo+pgymHwhV9A1qtQiNzq4XoONycMqgcjpzqzWU3ISO4EbSfA6eoZ0VrrJJkqsbF2f/x66Zz9Y0Yk8my/v8RkzvyNXdGQIi8hiou9k5j5ODuY+Rc9wv14a7nWpnrh4CJajjxsEY8J9H3X7wMYHrwhwYSJYdVSiQDbbdllzFTTL4RcYtljl6Uos/hs1L+k0qk2O52CGpdoTS9fAXBfRjeQrFZHuE95IS4euF6KsPyUR7LNDRTUn4EBxxvx10C0vuuXGLpRYWsvK6o= # CRYPTO_AES_KEY
language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
